FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

COPY LLM-Prop/ /home/LLM-Prop
COPY GPT-MolBERTa/ /home/GPT-MolBERTa
COPY requirements.txt /home

RUN apt-get update -y && apt-get install -y --no-install-recommends\
    vim \
    curl \
    ssh \
    ca-certificates \
    sudo\
    pip
#    apt-utils \
#    git \
#    bzip2 \
#    libx11-6 \
#    tree \
#    make \
#    build-essential \
#    libssl-dev \
#    zlib1g-dev \
#    libbz2-dev \
#    libreadline-dev \
#    libsqlite3-dev \
#    wget \
#    llvm \
#    libncursesw5-dev \
#    xz-utils \
#    tk-dev \
#    libxml2-dev \
#    libxmlsec1-dev \
#    libffi-dev \
#    liblzma-dev \
#    python3-openssl

RUN cd /home && \
    pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --trusted-host download.pytorch.org --index-url https://download.pytorch.org/whl/cu118 && \
    pip install -r requirements.txt
